In [1]:
import numpy as np
import pandas as pd

In [2]:
#Reading the data
mobile_data = pd.read_csv(r'C:\Users\smit\Downloads\MarketPositioningofMobile\Market Positioning of Mobile\Dataset\Mobile_data.csv')

In [3]:
print(mobile_data.shape)

(2000, 15)


In [4]:
mobile_data.head()

battery_power  clock_speed  fc  int_memory  m_dep  mobile_wt  n_cores  pc  \
0            842          2.2   1           7    0.6        188        2   2   
1           1021          0.5   0          53    0.7        136        3   6   
2            563          0.5   2          41    0.9        145        5   6   
3            615          2.5   0          10    0.8        131        6   9   
4           1821          1.2  13          44    0.6        141        2  14   

   px_height  px_width   ram  sc_h  sc_w  talk_time  price_range  
0         20       756  2549     9     7         19            1  
1        905      1988  2631    17     3          7            2  
2       1263      1716  2603    11     2          9            2  
3       1216      1786  2769    16     8         11            2  
4       1208      1212  1411     8     2         15            1

In [5]:
mobile_data.columns

Index(['battery_power', 'clock_speed', 'fc', 'int_memory', 'm_dep',
       'mobile_wt', 'n_cores', 'pc', 'px_height', 'px_width', 'ram', 'sc_h',
       'sc_w', 'talk_time', 'price_range'],
      dtype='object')

In [6]:
mobile_data=mobile_data[['battery_power', 'clock_speed', 'fc', 'int_memory', 'm_dep',
       'mobile_wt', 'n_cores', 'pc', 'px_height', 'px_width', 'ram', 'sc_h',
       'sc_w','talk_time', 'price_range']]

In [7]:
print(mobile_data.shape)

(2000, 15)


In [8]:
mobile_data.describe(include='all')

battery_power  clock_speed           fc   int_memory        m_dep  \
count    2000.000000  2000.000000  2000.000000  2000.000000  2000.000000   
mean     1238.518500     1.522250     4.309500    32.046500     0.501750   
std       439.418206     0.816004     4.341444    18.145715     0.288416   
min       501.000000     0.500000     0.000000     2.000000     0.100000   
25%       851.750000     0.700000     1.000000    16.000000     0.200000   
50%      1226.000000     1.500000     3.000000    32.000000     0.500000   
75%      1615.250000     2.200000     7.000000    48.000000     0.800000   
max      1998.000000     3.000000    19.000000    64.000000     1.000000   

         mobile_wt      n_cores           pc    px_height     px_width  \
count  2000.000000  2000.000000  2000.000000  2000.000000  2000.000000   
mean    140.249000     4.520500     9.916500   645.108000  1251.515500   
std      35.399655     2.287837     6.064315   443.780811   432.199447   
min      80.000000     1.000000     0.000000     0.000000   500.000000   
25%     109.000000     3.000000     5.000000   282.750000   874.750000   
50%     141.000000     4.000000    10.000000   564.000000  1247.000000   
75%     170.000000     7.000000    15.000000   947.250000  1633.000000   
max     200.000000     8.000000    20.000000  1960.000000  1998.000000   

               ram         sc_h         sc_w    talk_time  price_range  
count  2000.000000  2000.000000  2000.000000  2000.000000  2000.000000  
mean   2124.213000    12.306500     5.767000    11.011000     1.500000  
std    1084.732044     4.213245     4.356398     5.463955     1.118314  
min     256.000000     5.000000     0.000000     2.000000     0.000000  
25%    1207.500000     9.000000     2.000000     6.000000     0.750000  
50%    2146.500000    12.000000     5.000000    11.000000     1.500000  
75%    3064.500000    16.000000     9.000000    16.000000     2.250000  
max    3998.000000    19.000000    18.000000    20.000000     3.000000

In [9]:
#Finding missing values
print(mobile_data.isnull().sum())

battery_power    0
clock_speed      0
fc               0
int_memory       0
m_dep            0
mobile_wt        0
n_cores          0
pc               0
px_height        0
px_width         0
ram              0
sc_h             0
sc_w             0
talk_time        0
price_range      0
dtype: int64


In [10]:
#To check if there are any special characters in place of values 
for i in mobile_data.columns:
    print({i:mobile_data[i].unique()})

{'battery_power': array([ 842, 1021,  563, ..., 1139, 1467,  858], dtype=int64)}
{'clock_speed': array([2.2, 0.5, 2.5, 1.2, 1.7, 0.6, 2.9, 2.8, 2.1, 1. , 0.9, 1.1, 2.6,
       1.4, 1.6, 2.7, 1.3, 2.3, 2. , 1.8, 3. , 1.5, 1.9, 2.4, 0.8, 0.7])}
{'fc': array([ 1,  0,  2, 13,  3,  4,  5,  7, 11, 12, 16,  6, 15,  8,  9, 10, 18,
       17, 14, 19], dtype=int64)}
{'int_memory': array([ 7, 53, 41, 10, 44, 22, 24,  9, 33, 17, 52, 46, 13, 23, 49, 19, 39,
       47, 38,  8, 57, 51, 21,  5, 60, 61,  6, 11, 50, 34, 20, 27, 42, 40,
       64, 14, 63, 43, 16, 48, 12, 55, 36, 30, 45, 29, 58, 25,  3, 54, 15,
       37, 31, 32,  4, 18,  2, 56, 26, 35, 59, 28, 62], dtype=int64)}
{'m_dep': array([0.6, 0.7, 0.9, 0.8, 0.1, 0.5, 1. , 0.3, 0.4, 0.2])}
{'mobile_wt': array([188, 136, 145, 131, 141, 164, 139, 187, 174,  93, 182, 177, 159,
       198, 185, 196, 121, 101,  81, 156, 199, 114, 111, 132, 143,  96,
       200,  88, 150, 107, 100, 157, 160, 119,  87, 152, 166, 110, 118,
       162, 127, 109, 102, 104, 

In [11]:
mobile_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   battery_power  2000 non-null   int64  
 1   clock_speed    2000 non-null   float64
 2   fc             2000 non-null   int64  
 3   int_memory     2000 non-null   int64  
 4   m_dep          2000 non-null   float64
 5   mobile_wt      2000 non-null   int64  
 6   n_cores        2000 non-null   int64  
 7   pc             2000 non-null   int64  
 8   px_height      2000 non-null   int64  
 9   px_width       2000 non-null   int64  
 10  ram            2000 non-null   int64  
 11  sc_h           2000 non-null   int64  
 12  sc_w           2000 non-null   int64  
 13  talk_time      2000 non-null   int64  
 14  price_range    2000 non-null   int64  
dtypes: float64(2), int64(13)
memory usage: 234.5 KB


In [12]:
#Create X & Y 
X = mobile_data.values[:,0:-1]
Y = mobile_data.values[:,-1]

In [13]:
print(X.shape)
print(Y.shape)

(2000, 14)
(2000,)


In [14]:
from sklearn.preprocessing import StandardScaler

scaler=StandardScaler()

scaler.fit(X)
X = scaler.transform(X)

In [15]:
print(X)

[[-0.90259726  0.83077942 -0.76249466 ... -0.78498329  0.2831028
   1.46249332]
 [-0.49513857 -1.2530642  -0.99289039 ...  1.11426556 -0.63531667
  -0.73426721]
 [-1.5376865  -1.2530642  -0.53209893 ... -0.31017108 -0.86492153
  -0.36814045]
 ...
 [ 1.53077336 -0.76274805 -0.76249466 ... -0.78498329 -1.0945264
  -1.10039396]
 [ 0.62252745 -0.76274805 -0.07130748 ...  1.35167167  0.9719174
   1.46249332]
 [-1.65833069  0.58562134  0.15908825 ...  1.58907778 -0.4057118
  -1.6495841 ]]


In [16]:
from sklearn.model_selection import train_test_split  #<1000=in range of 80-20  &  >1000=in range of 70-30

#Split the data into test and train
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.3,random_state=10)

In [17]:
print(X_train.shape)
print(Y_train.shape)
print(X_test.shape)
print(Y_test.shape)

(1400, 14)
(1400,)
(600, 14)
(600,)


In [18]:
#predicting using the KNeighbors_Classifier
from sklearn.neighbors import KNeighborsClassifier
model_KNN=KNeighborsClassifier(n_neighbors=int(np.sqrt(len(X_train))),
                              metric='euclidean')

#euclidean,manhattan,minkowski
#fit the model on the data and predict the values
model_KNN.fit(X_train,Y_train)

Y_pred=model_KNN.predict(X_test)
print(list(zip(Y_test,Y_pred)))

[(3.0, 3.0), (3.0, 2.0), (2.0, 1.0), (3.0, 3.0), (1.0, 0.0), (3.0, 3.0), (3.0, 2.0), (3.0, 3.0), (1.0, 0.0), (3.0, 3.0), (2.0, 2.0), (3.0, 2.0), (0.0, 0.0), (1.0, 1.0), (0.0, 0.0), (3.0, 3.0), (2.0, 2.0), (3.0, 3.0), (2.0, 3.0), (2.0, 2.0), (3.0, 3.0), (2.0, 2.0), (0.0, 0.0), (1.0, 1.0), (0.0, 0.0), (0.0, 2.0), (3.0, 3.0), (3.0, 3.0), (1.0, 2.0), (1.0, 1.0), (2.0, 2.0), (0.0, 1.0), (3.0, 3.0), (2.0, 2.0), (2.0, 1.0), (2.0, 2.0), (1.0, 0.0), (1.0, 0.0), (2.0, 2.0), (0.0, 0.0), (3.0, 3.0), (2.0, 2.0), (2.0, 1.0), (0.0, 1.0), (1.0, 1.0), (3.0, 3.0), (1.0, 1.0), (0.0, 0.0), (1.0, 0.0), (2.0, 2.0), (1.0, 1.0), (3.0, 2.0), (2.0, 3.0), (3.0, 3.0), (2.0, 2.0), (3.0, 3.0), (2.0, 2.0), (3.0, 3.0), (0.0, 0.0), (0.0, 0.0), (1.0, 1.0), (1.0, 2.0), (0.0, 0.0), (0.0, 0.0), (2.0, 2.0), (0.0, 0.0), (2.0, 2.0), (1.0, 0.0), (1.0, 2.0), (3.0, 2.0), (2.0, 3.0), (2.0, 2.0), (1.0, 0.0), (1.0, 0.0), (3.0, 3.0), (2.0, 2.0), (3.0, 2.0), (3.0, 2.0), (2.0, 2.0), (1.0, 1.0), (3.0, 2.0), (0.0, 0.0), (1.0, 1.0), (0.

In [19]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report:")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test,Y_pred)
print("Accuracy of the model: ",acc)

[[119  20   1   0]
 [ 48  75  32   2]
 [  3  30  96  28]
 [  0   1  51  94]]
Classification report:
              precision    recall  f1-score   support

         0.0       0.70      0.85      0.77       140
         1.0       0.60      0.48      0.53       157
         2.0       0.53      0.61      0.57       157
         3.0       0.76      0.64      0.70       146

    accuracy                           0.64       600
   macro avg       0.65      0.65      0.64       600
weighted avg       0.64      0.64      0.64       600

Accuracy of the model:  0.64


In [20]:
from sklearn.model_selection import train_test_split  #<1000=in range of 80-20  &  >1000=in range of 70-30

#Split the data into test and train
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.3,random_state=10)

In [21]:
#predicting using the KNeighbors_Classifier
from sklearn.neighbors import KNeighborsClassifier
model_KNN=KNeighborsClassifier(n_neighbors=int(np.sqrt(len(X_train))),
                              metric='manhattan')

#euclidean,manhattan,minkowski
#fit the model on the data and predict the values
model_KNN.fit(X_train,Y_train)

Y_pred=model_KNN.predict(X_test)
print(list(zip(Y_test,Y_pred)))

[(3.0, 3.0), (3.0, 2.0), (2.0, 1.0), (3.0, 3.0), (1.0, 0.0), (3.0, 3.0), (3.0, 2.0), (3.0, 3.0), (1.0, 1.0), (3.0, 3.0), (2.0, 2.0), (3.0, 3.0), (0.0, 0.0), (1.0, 1.0), (0.0, 0.0), (3.0, 3.0), (2.0, 1.0), (3.0, 3.0), (2.0, 3.0), (2.0, 2.0), (3.0, 3.0), (2.0, 3.0), (0.0, 0.0), (1.0, 1.0), (0.0, 0.0), (0.0, 0.0), (3.0, 2.0), (3.0, 3.0), (1.0, 0.0), (1.0, 1.0), (2.0, 2.0), (0.0, 1.0), (3.0, 3.0), (2.0, 3.0), (2.0, 2.0), (2.0, 2.0), (1.0, 1.0), (1.0, 0.0), (2.0, 1.0), (0.0, 0.0), (3.0, 3.0), (2.0, 2.0), (2.0, 1.0), (0.0, 0.0), (1.0, 1.0), (3.0, 3.0), (1.0, 1.0), (0.0, 0.0), (1.0, 0.0), (2.0, 2.0), (1.0, 1.0), (3.0, 2.0), (2.0, 2.0), (3.0, 2.0), (2.0, 3.0), (3.0, 3.0), (2.0, 2.0), (3.0, 3.0), (0.0, 0.0), (0.0, 0.0), (1.0, 1.0), (1.0, 2.0), (0.0, 0.0), (0.0, 0.0), (2.0, 2.0), (0.0, 0.0), (2.0, 2.0), (1.0, 0.0), (1.0, 2.0), (3.0, 2.0), (2.0, 3.0), (2.0, 2.0), (1.0, 1.0), (1.0, 1.0), (3.0, 3.0), (2.0, 2.0), (3.0, 3.0), (3.0, 3.0), (2.0, 2.0), (1.0, 1.0), (3.0, 2.0), (0.0, 0.0), (1.0, 1.0), (0.

In [22]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report:")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test,Y_pred)
print("Accuracy of the model: ",acc)

[[125  15   0   0]
 [ 34  93  30   0]
 [  1  31 103  22]
 [  0   1  35 110]]
Classification report:
              precision    recall  f1-score   support

         0.0       0.78      0.89      0.83       140
         1.0       0.66      0.59      0.63       157
         2.0       0.61      0.66      0.63       157
         3.0       0.83      0.75      0.79       146

    accuracy                           0.72       600
   macro avg       0.72      0.72      0.72       600
weighted avg       0.72      0.72      0.72       600

Accuracy of the model:  0.7183333333333334


In [23]:
from sklearn.model_selection import train_test_split  #<1000=in range of 80-20  &  >1000=in range of 70-30

#Split the data into test and train
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.3,random_state=10)

In [24]:
#predicting using the KNeighbors_Classifier
from sklearn.neighbors import KNeighborsClassifier
model_KNN=KNeighborsClassifier(n_neighbors=int(np.sqrt(len(X_train))),
                              metric='minkowski')

#euclidean,manhattan,minkowski
#fit the model on the data and predict the values
model_KNN.fit(X_train,Y_train)

Y_pred=model_KNN.predict(X_test)
print(list(zip(Y_test,Y_pred)))

[(3.0, 3.0), (3.0, 2.0), (2.0, 1.0), (3.0, 3.0), (1.0, 0.0), (3.0, 3.0), (3.0, 2.0), (3.0, 3.0), (1.0, 0.0), (3.0, 3.0), (2.0, 2.0), (3.0, 2.0), (0.0, 0.0), (1.0, 1.0), (0.0, 0.0), (3.0, 3.0), (2.0, 2.0), (3.0, 3.0), (2.0, 3.0), (2.0, 2.0), (3.0, 3.0), (2.0, 2.0), (0.0, 0.0), (1.0, 1.0), (0.0, 0.0), (0.0, 2.0), (3.0, 3.0), (3.0, 3.0), (1.0, 2.0), (1.0, 1.0), (2.0, 2.0), (0.0, 1.0), (3.0, 3.0), (2.0, 2.0), (2.0, 1.0), (2.0, 2.0), (1.0, 0.0), (1.0, 0.0), (2.0, 2.0), (0.0, 0.0), (3.0, 3.0), (2.0, 2.0), (2.0, 1.0), (0.0, 1.0), (1.0, 1.0), (3.0, 3.0), (1.0, 1.0), (0.0, 0.0), (1.0, 0.0), (2.0, 2.0), (1.0, 1.0), (3.0, 2.0), (2.0, 3.0), (3.0, 3.0), (2.0, 2.0), (3.0, 3.0), (2.0, 2.0), (3.0, 3.0), (0.0, 0.0), (0.0, 0.0), (1.0, 1.0), (1.0, 2.0), (0.0, 0.0), (0.0, 0.0), (2.0, 2.0), (0.0, 0.0), (2.0, 2.0), (1.0, 0.0), (1.0, 2.0), (3.0, 2.0), (2.0, 3.0), (2.0, 2.0), (1.0, 0.0), (1.0, 0.0), (3.0, 3.0), (2.0, 2.0), (3.0, 2.0), (3.0, 2.0), (2.0, 2.0), (1.0, 1.0), (3.0, 2.0), (0.0, 0.0), (1.0, 1.0), (0.

In [25]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report:")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test,Y_pred)
print("Accuracy of the model: ",acc)

[[119  20   1   0]
 [ 48  75  32   2]
 [  3  30  96  28]
 [  0   1  51  94]]
Classification report:
              precision    recall  f1-score   support

         0.0       0.70      0.85      0.77       140
         1.0       0.60      0.48      0.53       157
         2.0       0.53      0.61      0.57       157
         3.0       0.76      0.64      0.70       146

    accuracy                           0.64       600
   macro avg       0.65      0.65      0.64       600
weighted avg       0.64      0.64      0.64       600

Accuracy of the model:  0.64


In [26]:
#predicting using the Decision_Tree_Classifier
from sklearn.tree import DecisionTreeClassifier

model_DecisionTree=DecisionTreeClassifier(criterion="gini",random_state=10)

#fit the model on the data and predict the values
model_DecisionTree.fit(X_train,Y_train)
Y_pred=model_DecisionTree.predict(X_test)

In [27]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report:")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test,Y_pred)
print("Accuracy of the model: ",acc)

[[128  12   0   0]
 [ 15 131  11   0]
 [  0  19 117  21]
 [  0   0  13 133]]
Classification report:
              precision    recall  f1-score   support

         0.0       0.90      0.91      0.90       140
         1.0       0.81      0.83      0.82       157
         2.0       0.83      0.75      0.79       157
         3.0       0.86      0.91      0.89       146

    accuracy                           0.85       600
   macro avg       0.85      0.85      0.85       600
weighted avg       0.85      0.85      0.85       600

Accuracy of the model:  0.8483333333333334


In [28]:
#predicting using the Decision_Tree_Classifier
from sklearn.tree import DecisionTreeClassifier

model_DecisionTree=DecisionTreeClassifier(criterion="entropy",random_state=10)

#fit the model on the data and predict the values
model_DecisionTree.fit(X_train,Y_train)
Y_pred=model_DecisionTree.predict(X_test)

In [29]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report:")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test,Y_pred)
print("Accuracy of the model: ",acc)

[[125  15   0   0]
 [ 11 135  11   0]
 [  0  27 108  22]
 [  0   0  17 129]]
Classification report:
              precision    recall  f1-score   support

         0.0       0.92      0.89      0.91       140
         1.0       0.76      0.86      0.81       157
         2.0       0.79      0.69      0.74       157
         3.0       0.85      0.88      0.87       146

    accuracy                           0.83       600
   macro avg       0.83      0.83      0.83       600
weighted avg       0.83      0.83      0.83       600

Accuracy of the model:  0.8283333333333334


In [30]:
#predicting using ada boost classifier
from sklearn.ensemble import AdaBoostClassifier
model_AdaBoost=AdaBoostClassifier(base_estimator=DecisionTreeClassifier(random_state=10),n_estimators=100,random_state=20)
model_AdaBoost.fit(X_train,Y_train)
Y_pred=model_AdaBoost.predict(X_test)

In [31]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report:")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test,Y_pred)
print("Accuracy of the model: ",acc)

[[128  12   0   0]
 [ 19 127  11   0]
 [  0  18 114  25]
 [  0   0  16 130]]
Classification report:
              precision    recall  f1-score   support

         0.0       0.87      0.91      0.89       140
         1.0       0.81      0.81      0.81       157
         2.0       0.81      0.73      0.77       157
         3.0       0.84      0.89      0.86       146

    accuracy                           0.83       600
   macro avg       0.83      0.83      0.83       600
weighted avg       0.83      0.83      0.83       600

Accuracy of the model:  0.8316666666666667


In [32]:
from sklearn.ensemble import GradientBoostingClassifier

model_GradientBoosting=GradientBoostingClassifier(n_estimators=200, random_state=10)

#fit the model on the data and predict the values
model_GradientBoosting.fit(X_train,Y_train)

Y_pred=model_GradientBoosting.predict(X_test)

In [33]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report:")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test,Y_pred)
print("Accuracy of the model: ",acc)

[[131   9   0   0]
 [  8 144   5   0]
 [  0  13 136   8]
 [  0   0   8 138]]
Classification report:
              precision    recall  f1-score   support

         0.0       0.94      0.94      0.94       140
         1.0       0.87      0.92      0.89       157
         2.0       0.91      0.87      0.89       157
         3.0       0.95      0.95      0.95       146

    accuracy                           0.92       600
   macro avg       0.92      0.92      0.92       600
weighted avg       0.92      0.92      0.92       600

Accuracy of the model:  0.915


In [34]:
from xgboost import XGBClassifier

model_GradientBoosting=XGBClassifier(n_estimators=200, random_state=10)

#fit the model on the data and predict the values
model_GradientBoosting.fit(X_train,Y_train)

Y_pred=model_GradientBoosting.predict(X_test)

[18:43:50] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.1/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


C:\Users\smit\Anaconda3\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


In [35]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report:")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test,Y_pred)
print("Accuracy of the model: ",acc)

[[131   9   0   0]
 [ 11 142   4   0]
 [  0  11 134  12]
 [  0   0  10 136]]
Classification report:
              precision    recall  f1-score   support

         0.0       0.92      0.94      0.93       140
         1.0       0.88      0.90      0.89       157
         2.0       0.91      0.85      0.88       157
         3.0       0.92      0.93      0.93       146

    accuracy                           0.91       600
   macro avg       0.91      0.91      0.91       600
weighted avg       0.91      0.91      0.90       600

Accuracy of the model:  0.905


1. firstly after using KNN algorithms we can see models accuracy was not so good.
2. But after using different algorithms we can see model was predicting better and it's accuracy was getting better.
3. And finally we can see Gradient Boosting Classifier gave us the best accuracy.